#!/usr/bin/env python3

"""Aggregate benchmark outputs into a performance dashboard.

This utility scans a directory containing JSON performance metrics, generates
plots and updates ``docs/performance.md`` to embed the resulting figures.  It
is intended to automate creation of the performance dashboard used in the
documentation.

The script expects the metrics directory to contain files with the following
names:

``strong_scaling.json``
    Mapping describing strong scaling behaviour.
``weak_scaling.json``
    Mapping describing weak scaling behaviour.
``io_throughput.json``
    Parallel I/O throughput measurements.
``roofline.json``
    Arithmetic intensity vs performance data for Roofline analysis.

Each JSON file may either contain ``{"x": [...], "y": [...]}`` arrays or a
list of ``[x, y]`` pairs.  Generated plots are saved into ``docs/images`` and
``docs/performance.md`` is updated to reference the figures.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable, Sequence

import matplotlib.pyplot as plt


def _load_series(path: Path) -> tuple[Sequence[float], Sequence[float]]:
    """Load an ``x``/``y`` series from ``path``.

    The JSON file may contain a mapping with ``x`` and ``y`` arrays or a list of
    ``[x, y]`` pairs.
    """

    data = json.loads(path.read_text())
    if isinstance(data, dict) and "x" in data and "y" in data:
        return data["x"], data["y"]
    if isinstance(data, list):
        xs = [p[0] for p in data]
        ys = [p[1] for p in data]
        return xs, ys
    raise ValueError(f"Unsupported data format in {path}")


def _plot_series(
    x: Sequence[float],
    y: Sequence[float],
    *,
    title: str,
    xlabel: str,
    ylabel: str,
    output: Path,
) -> None:
    """Create a simple line plot for the given series."""

    output.parent.mkdir(parents=True, exist_ok=True)
    plt.figure()
    plt.plot(x, y, marker="o")
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.grid(True)
    plt.savefig(output)
    plt.close()


def _update_markdown(entries: Iterable[tuple[str, Path]]) -> None:
    """Insert references to generated plots into ``docs/performance.md``."""

    doc = Path("docs/performance.md")
    text = doc.read_text().rstrip()
    section_lines = [
        "## Performance Metrics",
        "",
        "The following plots were generated by `scripts/collect_performance_metrics.py`.",
        "",
    ]
    for title, img in entries:
        section_lines.append(f"### {title}")
        section_lines.append("")
        section_lines.append(f"![{title}]({img.as_posix()})")
        section_lines.append("")
    section = "\n".join(section_lines).rstrip() + "\n"
    if "## Performance Metrics" in text:
        pre, _ = text.split("## Performance Metrics", 1)
        text = pre.rstrip() + "\n\n" + section
    else:
        text = text + "\n\n" + section
    doc.write_text(text + "\n")


def collect(metrics_dir: Path) -> None:
    """Generate plots from JSON metrics in ``metrics_dir``."""

    mapping = {
        "strong_scaling.json": (
            "Strong Scaling",
            "Processes",
            "Speedup",
            Path("docs/images/strong_scaling.png"),
        ),
        "weak_scaling.json": (
            "Weak Scaling",
            "Processes",
            "Runtime",
            Path("docs/images/weak_scaling.png"),
        ),
        "io_throughput.json": (
            "Parallel I/O Throughput",
            "Processes",
            "GB/s",
            Path("docs/images/io_throughput.png"),
        ),
        "roofline.json": (
            "Roofline Analysis",
            "Arithmetic Intensity",
            "Performance (GFLOP/s)",
            Path("docs/images/roofline.png"),
        ),
    }
    entries: list[tuple[str, Path]] = []
    for fname, (title, xlabel, ylabel, out_path) in mapping.items():
        src = metrics_dir / fname
        if not src.exists():
            continue
        x, y = _load_series(src)
        _plot_series(x, y, title=title, xlabel=xlabel, ylabel=ylabel, output=out_path)
        entries.append((title, out_path.relative_to(Path("docs"))))

    if entries:
        _update_markdown(entries)


def main() -> None:  # pragma: no cover - CLI wrapper
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "metrics_dir",
        nargs="?",
        default="diagnostics/performance",
        help="Directory containing JSON metric files.",
    )
    args = parser.parse_args()
    collect(Path(args.metrics_dir))


if __name__ == "__main__":  # pragma: no cover - CLI entry
    main()

